### ISSUE TITLE
How to use it with *ngFor?

### ISSUE THREAD

**Issue by atoyansk** [dockleryxk/ng-simple-slideshow#123]
I have a list of images in my project which is been displaying with *ngFor, like this:

```
<div  *ngFor="let img of imgs">
       <img width="100%" [src]="img.url">
</div>
```
I've tried to include **ng-simple-slideshow** as shown below, but it displays an error:
```
<div *ngFor="let img of imgs">
    <slideshow [autoPlay]="false" [imageUrls]="img.url"></slideshow> 
 </div> 
```
The error:
```
URIError: Failed to decode param '/%'
    at decodeURIComponent (<anonymous>)
    at decode_param (\node_modules\express\lib\router\layer.js:172:12)
    at Layer.match (\node_modules\express\lib\router\layer.js:123:27)
    at matchLayer (\node_modules\express\lib\router\index.js:574:18)
    at next (\node_modules\express\lib\router\index.js:220:15)
    at expressInit (\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (\node_modules\express\lib\router\index.js:317:13)
    at \node_modules\express\lib\router\index.js:284:7
    at Function.process_params (\node_modules\express\lib\router\index.js:335:12)
    at next (\node_modules\express\lib\router\index.js:275:10)
    at query (\node_modules\express\lib\middleware\query.js:45:5)
    at Layer.handle [as handle_request] (\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (\node_modules\express\lib\router\index.js:317:13)
    at \node_modules\express\lib\router\index.js:284:7
    at Function.process_params (\node_modules\express\lib\router\index.js:335:12)
```

How can I implement **ng-simple-slideshow** in this case?

**Comment by dockleryxk** [comment]
@atoyansk you just put the array of images as the `imageUrls`, using ngFor with a slideshow for each image is going to cause trouble for sure.
